"""baseline: full schema as of broker/positions phase 1

Revision ID: 9d5140c06546
Revises: 
Create Date: 2026-09-22 19:42:30.324448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d5140c06546'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timeframes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symbols_total', sa.Integer(), nullable=False),
    sa.Column('symbols_ok', sa.Integer(), nullable=False),
    sa.Column('symbols_failed', sa.Integer(), nullable=False),
    sa.Column('candles_written', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('isin', sa.String(length=24), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    op.create_table('broker_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('credentials_enc', sa.Text(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('token_minted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_on', sa.Date(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=16), nullable=True),
    sa.Column('last_sync_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker', 'label', name='uq_broker_account')
    )
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('price_basis', sa.String(length=16), server_default='splits_only', nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'ts', name='uq_candle')
    )
    op.create_index(op.f('ix_candles_symbol_id'), 'candles', ['symbol_id'], unique=False)
    op.create_index('ix_candles_timeframe_ts', 'candles', ['timeframe', 'ts'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('ratio_from', sa.Float(), nullable=True),
    sa.Column('ratio_to', sa.Float(), nullable=True),
    sa.Column('price_factor', sa.Float(), nullable=True),
    sa.Column('is_extraordinary', sa.Boolean(), nullable=False),
    sa.Column('affects_share_count', sa.Boolean(), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'ex_date', 'action_type', name='uq_corp_action')
    )
    op.create_index('ix_corp_actions_ex_date', 'corporate_actions', ['ex_date'], unique=False)
    op.create_index('ix_corp_actions_symbol_ex', 'corporate_actions', ['symbol_id', 'ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_symbol_id'), 'corporate_actions', ['symbol_id'], unique=False)
    op.create_table('indicator_values',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atr_10', sa.Float(), nullable=True),
    sa.Column('supertrend_10_3', sa.Float(), nullable=True),
    sa.Column('supertrend_dir', sa.Integer(), nullable=True),
    sa.Column('macd_12_26', sa.Float(), nullable=True),
    sa.Column('macd_signal_9', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('ema_200', sa.Float(), nullable=True),
    sa.Column('adx_14', sa.Float(), nullable=True),
    sa.Column('bb_upper_20_2', sa.Float(), nullable=True),
    sa.Column('bb_middle_20_2', sa.Float(), nullable=True),
    sa.Column('bb_lower_20_2', sa.Float(), nullable=True),
    sa.Column('bb_bandwidth', sa.Float(), nullable=True),
    sa.Column('volume_ma_20', sa.Float(), nullable=True),
    sa.Column('kc_upper_20_15', sa.Float(), nullable=True),
    sa.Column('kc_middle_20', sa.Float(), nullable=True),
    sa.Column('kc_lower_20_15', sa.Float(), nullable=True),
    sa.Column('ttm_squeeze_on', sa.Boolean(), nullable=True),
    sa.Column('ttm_squeeze_off', sa.Boolean(), nullable=True),
    sa.Column('ttm_momentum', sa.Float(), nullable=True),
    sa.Column('rvol_20', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'ts', name='uq_indicator')
    )
    op.create_index(op.f('ix_indicator_values_symbol_id'), 'indicator_values', ['symbol_id'], unique=False)
    op.create_index('ix_indicators_timeframe_ts', 'indicator_values', ['timeframe', 'ts'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('strategy', sa.String(length=24), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_mode', sa.String(length=16), nullable=True),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=False),
    sa.Column('target_2', sa.Float(), nullable=False),
    sa.Column('risk_pct', sa.Float(), nullable=True),
    sa.Column('rr_ratio', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_strategy_ts', 'signals', ['strategy', 'ts'], unique=False)
    op.create_index('ix_signals_sym_tf_strat_ts', 'signals', ['symbol_id', 'timeframe', 'strategy', 'ts'], unique=False)
    op.create_index(op.f('ix_signals_symbol_id'), 'signals', ['symbol_id'], unique=False)
    op.create_index('ix_signals_ts', 'signals', ['ts'], unique=False)
    op.create_table('broker_holdings_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('isin', sa.String(length=24), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=32), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('t1_quantity', sa.Integer(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_account_id', 'as_of', 'isin', name='uq_holding_snapshot')
    )
    op.create_index(op.f('ix_broker_holdings_snapshots_broker_account_id'), 'broker_holdings_snapshots', ['broker_account_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('entry_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_open', sa.Integer(), nullable=False),
    sa.Column('qty_total', sa.Integer(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('avg_entry_price_raw', sa.Float(), nullable=False),
    sa.Column('structural_factor_applied', sa.Float(), nullable=False),
    sa.Column('last_restated_on', sa.Date(), nullable=True),
    sa.Column('matched_strategy', sa.String(length=24), nullable=True),
    sa.Column('matched_signal_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_timeframe', sa.String(length=4), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_reason', sa.String(length=128), nullable=True),
    sa.Column('is_unmatched', sa.Boolean(), nullable=False),
    sa.Column('frozen_entry', sa.Float(), nullable=True),
    sa.Column('frozen_stop', sa.Float(), nullable=True),
    sa.Column('frozen_target_1', sa.Float(), nullable=True),
    sa.Column('frozen_target_2', sa.Float(), nullable=True),
    sa.Column('frozen_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('exit_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('last_evaluated_on', sa.Date(), nullable=True),
    sa.Column('last_verdict', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_trade_id')
    )
    # entry_trade_id/exit_trade_id -> broker_trades.id are declared use_alter=True
    # on the model (positions<->broker_trades is a circular FK pair), so they are
    # deliberately left off the CREATE TABLE above and added below via
    # create_foreign_key, once broker_trades exists. (Autogenerate emits them
    # inline by default, but a plain CREATE TABLE silently drops use_alter
    # constraints instead of applying them — verified empty on the scratch DB —
    # so this was hand-edited.)
    op.create_index(op.f('ix_positions_symbol_id'), 'positions', ['symbol_id'], unique=False)
    op.create_index('ix_positions_symbol_status', 'positions', ['symbol_id', 'status'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_index('ix_positions_user_status', 'positions', ['user_id', 'status'], unique=False)
    op.create_table('broker_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=16), nullable=False),
    sa.Column('broker_trade_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('exchange_trade_id', sa.String(length=64), nullable=True),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('segment', sa.String(length=8), nullable=False),
    sa.Column('product', sa.String(length=8), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=32), nullable=False),
    sa.Column('isin', sa.String(length=24), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('trade_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_account_id', 'broker_trade_id', name='uq_broker_trade')
    )
    op.create_index(op.f('ix_broker_trades_broker_account_id'), 'broker_trades', ['broker_account_id'], unique=False)
    op.create_index('ix_broker_trades_symbol_date', 'broker_trades', ['symbol_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_broker_trades_symbol_id'), 'broker_trades', ['symbol_id'], unique=False)
    op.create_index('ix_broker_trades_user_date', 'broker_trades', ['user_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_broker_trades_user_id'), 'broker_trades', ['user_id'], unique=False)
    # positions<->broker_trades circular FKs (see note on the positions table
    # above): applied now that both tables exist.
    op.create_foreign_key(
        'fk_positions_entry_trade', 'positions', 'broker_trades',
        ['entry_trade_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_positions_exit_trade', 'positions', 'broker_trades',
        ['exit_trade_id'], ['id'],
    )
    op.create_table('position_evaluations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('bar_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('stop_level', sa.Float(), nullable=True),
    sa.Column('trail_level', sa.Float(), nullable=True),
    sa.Column('target_1', sa.Float(), nullable=True),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('supertrend_dir', sa.Integer(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=False),
    sa.Column('days_held', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'as_of', name='uq_position_eval')
    )
    op.create_index(op.f('ix_position_evaluations_position_id'), 'position_evaluations', ['position_id'], unique=False)
    op.create_table('sell_allocations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sell_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['sell_trade_id'], ['broker_trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sell_trade_id', 'position_id', name='uq_sell_allocation')
    )
    op.create_index(op.f('ix_sell_allocations_position_id'), 'sell_allocations', ['position_id'], unique=False)
    op.create_index(op.f('ix_sell_allocations_sell_trade_id'), 'sell_allocations', ['sell_trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the circular positions<->broker_trades FKs first: broker_trades is
    # dropped below, and these constraints (on positions) reference it.
    op.drop_constraint('fk_positions_exit_trade', 'positions', type_='foreignkey')
    op.drop_constraint('fk_positions_entry_trade', 'positions', type_='foreignkey')
    op.drop_index(op.f('ix_sell_allocations_sell_trade_id'), table_name='sell_allocations')
    op.drop_index(op.f('ix_sell_allocations_position_id'), table_name='sell_allocations')
    op.drop_table('sell_allocations')
    op.drop_index(op.f('ix_position_evaluations_position_id'), table_name='position_evaluations')
    op.drop_table('position_evaluations')
    op.drop_index(op.f('ix_broker_trades_user_id'), table_name='broker_trades')
    op.drop_index('ix_broker_trades_user_date', table_name='broker_trades')
    op.drop_index(op.f('ix_broker_trades_symbol_id'), table_name='broker_trades')
    op.drop_index('ix_broker_trades_symbol_date', table_name='broker_trades')
    op.drop_index(op.f('ix_broker_trades_broker_account_id'), table_name='broker_trades')
    op.drop_table('broker_trades')
    op.drop_index('ix_positions_user_status', table_name='positions')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index('ix_positions_symbol_status', table_name='positions')
    op.drop_index(op.f('ix_positions_symbol_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_broker_holdings_snapshots_broker_account_id'), table_name='broker_holdings_snapshots')
    op.drop_table('broker_holdings_snapshots')
    op.drop_index('ix_signals_ts', table_name='signals')
    op.drop_index(op.f('ix_signals_symbol_id'), table_name='signals')
    op.drop_index('ix_signals_sym_tf_strat_ts', table_name='signals')
    op.drop_index('ix_signals_strategy_ts', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_indicators_timeframe_ts', table_name='indicator_values')
    op.drop_index(op.f('ix_indicator_values_symbol_id'), table_name='indicator_values')
    op.drop_table('indicator_values')
    op.drop_index(op.f('ix_corporate_actions_symbol_id'), table_name='corporate_actions')
    op.drop_index('ix_corp_actions_symbol_ex', table_name='corporate_actions')
    op.drop_index('ix_corp_actions_ex_date', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index('ix_candles_timeframe_ts', table_name='candles')
    op.drop_index(op.f('ix_candles_symbol_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_table('ingest_runs')
    # ### end Alembic commands ###
